extends:
  - requarks
  - plugin:vue/strongly-recommended
env:
  node: true
  jest: true
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2020
  allowImportExportEverywhere: true
globals:
  document: false
  navigator: false
  window: false
  WIKI: true
ignorePatterns:
  - '**/node_modules/**'
  - '**/*.min.js'
  - 'assets/**'
  - 'coverage/**'
  - 'repo/**'
  - 'data/**'
  - 'logs/**'
  - 'server/locales/**'
